Improve error message of java command such as "SyntaxError: Unexpected token E".
Reproduction:
1. Update vnu.jar to latest version. (Download from https://github.com/validator/validator/)
2. Set JAVA_HOME to Java 7.
3. Run shell command:
    node -e "require('validator-nu').validate('')"

Console output:
undefined:1
Exception in thread "main" java.lang.UnsupportedClassVersionError: nu/validator/client/SimpleCommandLineValidator : Unsupported major.minor version 52.0
^

SyntaxError: Unexpected token E
    at Object.parse (native)
    at Socket.<anonymous> (/tmp/foo/node_modules/validator-nu/lib/validate.js:30:35)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)